import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import AnimatedText from '@/components/AnimatedText'
import Navbar from '@/components/Navbar'
import { motion, useMotionValue} from 'framer-motion'
import React, { useRef } from 'react'


import Accessory1 from '../../public/images/accessories/Accessories-01.png'
import Accessory2 from '../../public/images/accessories/Accessories-02.png'
import Accessory3 from '../../public/images/accessories/Accessories-03.png'
import Accessory4 from '../../public/images/accessories/Accessories-04.png'
import Accessory5 from '../../public/images/accessories/Accessories-05.png'
import Accessory6 from '../../public/images/accessories/Accessories-06.png'
import Accessory7 from '../../public/images/accessories/Accessories-07.png'
import Accessory8 from '../../public/images/accessories/Accessories-08.png'
import Accessory9 from '../../public/images/accessories/Accessories-09.png'
import Accessory10 from '../../public/images/accessories/Accessories-10.png'
import Accessory11 from '../../public/images/accessories/Accessories-11.png'
import Accessory12 from '../../public/images/accessories/Accessories-12.png'
import Accessory13 from '../../public/images/accessories/Accessories-13.png'




const Items = ({ img }) => {
    return (
        <motion.div
            initial={{ x: -200, opacity:0 }}
            whileInView={{ x: 0, opacity:1, transition: { duration: 0.9, ease: "easeInOut", staggerChildren:1} }}
            viewport={{ once: true }}
            whileHover={{scale:1.02}}
            transition={{ type: 'tween', staggerChildren: 1 }}
            className=""
        >
         <Image src={img} className='w-80 2xl:w-72 xl:w-60 lg:w-48 sm:w-42 m-6 lg:m-3 sm:m-1 mx-6 sm:mx-auto sm:my-3 rounded-xl border border-primaryDark/25 shadow-md' />
  
        </motion.div>
    )
}


export default function Home() {
    return (
        <>
            <Head>
                <title>UPC | Accessories</title>
                <meta name="description" content="Generated by create next app" />

            </Head>
            <Navbar className="bg-primarylight" />

            <main className="  flex  text-dark w-full min-h-screen 
      bg-primarylight  pb-0 mb-0 lg:items-start ">
                <Layout className=' pt-0 pb-0  bg-transparent '>
                    <AnimatedText text="Accessories" className='text-center ' />
                    <div className="flex items-center flex-wrap justify-start py-16 sm:justify-center">
                      <Items img={Accessory1} />
                      <Items img={Accessory2} />
                      <Items img={Accessory3} />
                      <Items img={Accessory4} />
                      <Items img={Accessory5} />
                      <Items img={Accessory6} />
                      <Items img={Accessory7} />
                      <Items img={Accessory8} />
                      <Items img={Accessory9} />
                      <Items img={Accessory10} />
                      <Items img={Accessory11} />
                      <Items img={Accessory12} />
                      <Items img={Accessory13} />
                      
                    </div>
                    


                </Layout>

            </main>

        </>
    )
}

