import React from 'react'
import flexitankbanner from '../../public/images/flexitanks/banner.jpg'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Layout from '@/components/Layout'
import Image from 'next/image'

import AnimatedText from '@/components/AnimatedText'

import FlexitankUses from '@/components/FlexitankUses'
import FlexitankCarry from '@/components/FlexitankCarry'
import FlexitankAdvantages from '@/components/FlexitankAdvantages'
import FlexitankCapacity from '@/components/FlexitankCapacity'
import FlexitankMisconception from '@/components/FlexitankMisconception'
import FlexitankxChange from '@/components/FlexitankxChange'

{/*  */ }






const flexitank = () => {
  return (
    <>
      <Head>
        <title>Flexitank</title>
        <meta name="description" content="Generated by create next app" />

      </Head>

      <Image src={flexitankbanner} alt="flexitank"
        className='  -z-10 absolute w-full min-h-screen mb-0 object-cover 
             '
        priority
        sizes="(max-width: 768px) 100vw,
            (max-width: 1200px) 50vw,       
            33vw"
      />

<main className="  flex flex-col  text-dark w-full min-h-screen 
   bg-gradient-to-r bg-top from-[#F0E7D5] to-[#904C06]/80  pb-0 mb-0 lg:items-start ">
        <Navbar className='bg-transparent z-20' />
        <Layout className=' pt-0 pb-0 items-center bg-transparent '>
          <div className='flex flex-col lg:items-center text-dark'>
            <div className='w-3/5 xl:w-full lg:w-full'>
              <AnimatedText text="Crown Flexitanks"
                className='   pt-24 2xl:pt-6 xl:pt-3 lg:pt-16 sm:pt-6 text-dark !text-8xl !text-left xl:!text-6xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-5xl ' />
              <p className='pt-12 pr-24 sm:pr-0 text-2xl 2xl:text-xl md:text-lg sm:text-base  '>
              The flexitanks commonly used by the industry can hold up to 24,000 liters of liquid cargo.
                Flexitanks are used for the transportation of non-hazardous liquids.</p>

            </div>
          </div>
        </Layout>
      </main>

      <FlexitankUses />
      <FlexitankCarry />
      <FlexitankAdvantages />
      <FlexitankCapacity />
      <FlexitankMisconception />
      <FlexitankxChange />

    </>
  )
}

export default flexitank

{/* <Image src={flexitankbanner} alt="flexitank"
        className='-z-10 absolute w-full h-screen mb-0 object-cover'
        priority
        sizes="(max-width: 768px) 100vw,
            (max-width: 1200px) 50vw,       
            33vw"/>

      <main className="flex flex-col  text-dark  w-full min-h-screen h-screen
   bg-gradient-to-r bg-top from-[#F0E7D5] to-[#904C06]/80  pb-0 mb-0 lg:items-start ">
        <Navbar className='bg-transparent' />
        <Layout className=' pt-0 pb-0 items-center bg-transparent '>
          <div className='flex flex-row lg:items-center  text-dark'>
            <div className='w-3/5 xl:w-4/5 lg:w-full'>
              <div className="my-32 lg:hidden"></div>
              <AnimatedText text="Crown Flexitanks"
                className='mt-20 text-dark !text-8xl !text-left xl:!text-7xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-5xl sm:pt-6' />
            </div>
            <div className='flex flex-col ml-28 mt-20'>

              <p className='my-6 mt-12 pr-24 sm:pr-0 text-2xl xl:text-xl md:text-lg sm:text-base font-light '>The flexitanks commonly used by the industry can hold up to 24,000 liters of liquid cargo.
                Flexitanks are used for the transportation of non-hazardous liquids.</p>
              <p className='my-6  pr-24 sm:pr-0 text-2xl xl:text-xl md:text-lg sm:text-base font-light '>
                To give a technical definition: "Hermetically sealed, collapsible, and flexible bag or
                bladder, which is fitted into a twenty-foot Dry Van (DV) or standard conatainer."</p>
            </div>

          </div>
          <div className="w-2/5 xl:w-1/5"></div>

        </Layout>

      </main> */ }